config/routes.rb
Rails
  .application
  .routes
  .draw do
    # get 'submissions/show'
    # get 'submissions/new'
    root 'submissions#new', as: :index

    # Submissions routing

    constraints Clearance::Constraints::SignedIn.new do
      get 'submissions/export' => 'submissions#export', :as => 'export'
      resources :submissions
    end

    constraints Clearance::Constraints::SignedOut.new do
      get 'submissions/export', to: redirect('/sign_in')
      resources :submissions, only: %i[new create]
      resources :submissions, to: redirect('/sign_in')
    end

    # Clearance routing
    resources :passwords,
              controller: 'clearance/passwords',
              only: %i[create new]

    resource :session, controller: 'clearance/sessions', only: [:create]

    resources :users,
              controller: 'clearance/users',
              only: Clearance.configuration.user_actions do
      resource :password,
               controller: 'clearance/passwords',
               only: %i[edit update]
    end

    get '/sign_in' => 'clearance/sessions#new', :as => 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', :as => 'sign_out'

    if Clearance.configuration.allow_sign_up?
      get '/sign_up' => 'clearance/users#new', :as => 'sign_up'
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
require 'csv'

class Submission < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  #attr_accessor :privacy_policy

  has_one_attached :image

  validates :name, presence: false, length: { maximum: 255 }
  validates :image,
            presence: true,
            blob: { content_type: :image, size_range: 0..10.megabytes }
  validates :privacy_policy, acceptance: true

  #validates :breed, presence: true

  def self.to_csv
    attributes = %w[id name breed]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each { |contact| csv << attributes.map { |attr| contact.send(attr) } }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  include ActiveStorage::SendZip

  def index
    @submissions = Submission.all
  end

  def new
    @submission = Submission.new
    @count = Submission.count
  end

  def create
    @submission = Submission.new(submission_params)
    @count = Submission.count
    if @submission.save
      flash[:success] = 'Dog uploaded successfully! Thank you!'
      redirect_to :index
    else
      render 'new'
    end
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.update(submission_params)
      flash[:success] = 'Update saved'
      redirect_to :submissions
    else
      render 'edit'
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    flash[:success] = 'Submission destroyed' if @submission.destroy
    redirect_to :submissions
  end

  def export
    @submissions = Submission.all
    respond_to do |format|
      format.html { render }
      format.csv do
        send_data @submissions.to_csv, filename: 'dog_pics_database.csv'
      end
      format.zip do
        send_zip(
          Hash[
            @submissions.map do |submission|
              [format('%03d', submission.id), submission.image]
            end
          ],
          filename: 'dog_pics.zip',
        )
        #send_zip(
        #  @submissions.map do |submission|
        #    sub = submission.image.blob
        #    sub.update(
        #      filename:
        #        "#{submission.id}.#{submission.image.filename.extension}",
        #    )
        #    return sub
        #  end,
        #  filename: 'dog_images.zip',
        #)
      end
    end
  end

  private

  def submission_params
    # It's mandatory to specify the nested attributes that should be permitted.
    # If you use `permit` with just the key that points to the nested attributes hash,
    # it will return an empty hash.
    params
      .require(:submission)
      .permit(
        :name,
        :breed,
        :image,
        :commit,
        :authenticity_token,
        :privacy_policy,
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/submission_helper.rb
module SubmissionHelper
end

app/helpers/submit_helper.rb
module SubmitHelper
end

app/views/layouts/_footer.html.erb
<div>
</div>

app/views/layouts/_header.html.erb
<div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Give Me Your Dogs (Please)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="main-container">
      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%=
      message %></div>
        <% end %>
        <% if signed_in? %>
        <hr />
          <p>
            Signed in as: <%= current_user.email %>
            <%= link_to "Home", "/submissions/new" %>
            <%= link_to "List", "/submissions" %>
            <%= link_to "Export", :export %>
            <%= button_to 'Sign out', sign_out_path, method: :delete %>
          </p>
        <% end %>
        <%= render 'layouts/footer' %>
        <!-- <%= debug(params) if Rails.env.development? %> -->
      </div>
    </body>
  </html>

app/views/shared/_error_messages.html.erb
<% if @submission.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@submission.errors.count, "error") %>.
        </div>
        <ul>
        <% @submission.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/submissions/_upload_form.html.erb
<%= form_with(model: @submission, local: true) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :name, 'Name for attribution (optional)' %>
  <%= f.text_field :name %>
  <%= f.label :breed, 'Breed of dog in the photo (optional)' %>
  <%= f.text_field :breed %>
  <p>
    <%= f.check_box :privacy_policy %>
    <%= f.label :privacy_policy, "I agree to the #{link_to('privacy policy', 'privacy_policy.md', target: :_blank)}.".html_safe %>
  </p>
  <%= f.label :image, 'Upload Image' %>
  <%= f.file_field :image, multiple: false, direct_upload: true %>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/submissions/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit submission</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @submission, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :breed %>
      <%= f.text_field :breed, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/submissions/export.html.erb
<h1>Export</h1>
<%= link_to('Export CSV', export_path(format: "csv")) %>
<%= link_to('Download images', export_path(format: "zip")) %>

app/views/submissions/index.html.erb
<h1>Listing</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Breed</th>
    <th>Image</th>
  </tr>
  <% @submissions.each do |submission| %>
    <tr>
      <td><%= submission.name %></td>
      <td><%= submission.breed %></td>
      <td>
        <%= link_to url_for(submission.image), target: :_blank do %>
          <%= image_tag submission.image.variant(resize_to_limit: [100, 100]) %>
        <% end %>
      </td>
      <td><%= link_to 'View', submission %></td>
      <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
      <td><%= link_to 'Delete', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/submissions/new.html.erb
<h1>Give Me Your Dogs (Please)</h1>
<section>
  <p>For my project I'm creating an app to help people learn to recognise different breeds of dog by sight. For that purpose, I need photographs of as many breeds of dog as possible!</p>
  <p>It would be a huge help if you could upload any pictures of your own dogs that you'd be okay with me using.</p>
  <address>- Zoey Child (<a href="mailto:imperialoctopus@gmail.com">imperialoctopus@gmail.com</a>)</address>
</section>
<hr/>
<section>
  <%= render 'upload_form' %>
  <%= javascript_pack_tag 'direct_upload' %>
  <%= stylesheet_link_tag 'direct_upload' %>
</section>
<hr/>
<p class="counter">Total dogs uploaded:
  <%= @count %></p>

app/views/submissions/show.html.erb
<h1>Submission <%= @submission.id %></h1>
<%= image_tag(@submission.image, class: "cover_image") %>
<%= link_to "Back", submissions_path %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>